py_binary(
    name = "server",
    srcs = ["server.py"],
    data = [
        "//py/tornado/chatroom/templates:room.html",
        "//py/tornado/chatroom/templates:room_list.html",
        "//py/tornado/chatroom/templates:login.html",
    ],
)